version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:  
      - app
  
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    networks:
      - app

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
        - "80:80"
    networks:  
        - app

networks: 
  app:
    driver: bridge