version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports: 
        - "5000:5000"
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
        - "80:80"
    links: 
        - app